# Generated by Django 3.0.1 on 2020-05-28 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kaohe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaohe_name', models.CharField(max_length=500)),
                ('kaohe_department', models.CharField(default='', max_length=20)),
                ('kaohe_kind', models.CharField(max_length=100)),
                ('kaohe_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='kaoheinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaoheinfo_user', models.CharField(max_length=20)),
                ('kaoheinfo_department', models.CharField(max_length=20)),
                ('kaoheinfo_month', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('kaoheinfo_monthtarget', models.IntegerField(blank=True, null=True)),
                ('kaoheinfo_monthtotal', models.IntegerField(blank=True, null=True)),
                ('kaoheinfo_monthfiprecent', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_user', models.CharField(max_length=20)),
                ('score_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('score_requiredepartment', models.CharField(default='', max_length=20)),
                ('score_requireusername', models.CharField(default='', max_length=20)),
                ('score_events', models.CharField(max_length=500)),
                ('score_kind', models.CharField(max_length=100)),
                ('score_pre', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_phone', models.CharField(default='', max_length=20)),
                ('user_department', models.CharField(max_length=50)),
                ('user_password', models.CharField(default='', max_length=128)),
                ('user_role', models.CharField(default='', max_length=20)),
                ('user_manager', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
