# Generated by Django 3.0.1 on 2020-04-22 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 16, 42, 7, 675413, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
