# Generated by Django 3.0.1 on 2020-04-24 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPI', '0002_auto_20200423_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='kaoheinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaoheinfo_user', models.CharField(max_length=20)),
                ('kaoheinfo_department', models.CharField(max_length=20)),
                ('kaoheinfo_month', models.DateTimeField(default=datetime.datetime(2020, 4, 24, 11, 26, 15, 531305), verbose_name='更新时间')),
                ('kaoheinfo_monthtarget', models.IntegerField(blank=True, null=True)),
                ('kaoheinfo_monthtotal', models.IntegerField(blank=True, null=True)),
                ('kaoheinfo_monthfiprecent', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_manager',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 11, 26, 15, 531305), verbose_name='更新时间'),
        ),
    ]
